name: CI pipeline


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run:
          pip install -r requirements.txt
          

      - name: Run flake8 linter
        run: 
             flake8 calculator2.py test.calculator.py --max-line-length=88 --extend-ignore=E203

      - name: Run tests
        if: success() 
        run: pytest test_calculator.py